import json
import logging
from typing import Any, Dict
from kubetag.domain import IssueEvent

logger = logging.getLogger(__name__)

class EventError(Exception):
    """Base exception for event processing errors."""
    pass

class MalformedEventError(EventError):
    """Raised when the event payload is invalid or cannot be parsed."""
    pass

class IgnoredEventError(EventError):
    """Raised when the event is valid but should be ignored (e.g., wrong action, PR, bot)."""
    pass

def parse_issue_event(event_path: str) -> IssueEvent:
    """Parse GitHub event payload from the given file path.
    
    Args:
        event_path: Path to the JSON event file.
        
    Returns:
        An IssueEvent domain object.
        
    Raises:
        MalformedEventError: If the file is not valid JSON or lacks critical fields.
        IgnoredEventError: If the event is for a pull request, bot user, or has an unsupported action.
    """
    try:
        with open(event_path, "r", encoding="utf-8") as f:
            payload = json.load(f)
    except FileNotFoundError as e:
        raise MalformedEventError(f"Event file not found: {event_path}") from e
    except json.JSONDecodeError as e:
        raise MalformedEventError(f"Malformed JSON in event file: {e}") from e
    except Exception as e:
        raise MalformedEventError(f"Failed to read event file: {e}") from e

    return parse_issue_payload(payload)

def parse_issue_payload(payload: Dict[str, Any]) -> IssueEvent:
    """Extract IssueEvent from a parsed payload dictionary.
    
    Args:
        payload: The parsed JSON event dict.
        
    Returns:
        An IssueEvent domain object.
        
    Raises:
        MalformedEventError: If critical fields are missing.
        IgnoredEventError: If it should be ignored according to rules.
    """
    issue = payload.get("issue")
    if not issue:
        raise MalformedEventError("Payload missing 'issue' object.")
        
    if "pull_request" in issue:
        raise IgnoredEventError("Ignoring event because it is a pull request.")
        
    action = payload.get("action")
    if not action:
        raise MalformedEventError("Payload missing 'action' field.")
        
    supported_actions = {"opened", "edited", "reopened"}
    if action not in supported_actions:
        raise IgnoredEventError(f"Ignoring unsupported action '{action}'. Supported: {supported_actions}")
        
    user = issue.get("user", {})
    user_type = user.get("type", "User")
    if user_type == "Bot":
        raise IgnoredEventError("Ignoring event because it was generated by a bot.")
        
    repository = payload.get("repository")
    if not repository:
        raise MalformedEventError("Payload missing 'repository' object.")
        
    owner_info = repository.get("owner", {})
    owner = owner_info.get("login")
    repo = repository.get("name")
    
    if not owner or not repo:
        raise MalformedEventError("Repository owner or name is missing.")
        
    issue_number = issue.get("number")
    title = issue.get("title")
    body = issue.get("body")
    html_url = issue.get("html_url")
    
    if issue_number is None or title is None or not html_url:
        raise MalformedEventError("Issue number, title, or html_url is missing.")
        
    try:
        issue_number_int = int(issue_number)
    except ValueError as e:
        raise MalformedEventError(f"Invalid issue number: {issue_number}") from e

    return IssueEvent(
        owner=owner,
        repo=repo,
        issue_number=issue_number_int,
        title=title,
        body=body,
        action=action,
        html_url=html_url,
    )
