from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from kubetag.domain import IssueEvent

SUPPORTED_ACTIONS = {"opened", "edited", "reopened"}


class EventError(Exception):
    pass


class MalformedEventError(EventError):
    pass


class IgnoredEventError(EventError):
    pass


def parse_issue_event(event_path: str) -> IssueEvent:
    try:
        payload = json.loads(Path(event_path).read_text(encoding="utf-8"))
    except FileNotFoundError as error:
        raise MalformedEventError(f"Event file not found: {event_path}") from error
    except OSError as error:
        raise MalformedEventError(
            f"Event file could not be read: {event_path}"
        ) from error
    except json.JSONDecodeError as error:
        raise MalformedEventError(f"Malformed JSON in event file: {error}") from error
    if not isinstance(payload, dict):
        raise MalformedEventError("Event payload must be a JSON object")
    return parse_issue_payload(payload)


def _object(payload: dict[str, Any], key: str) -> dict[str, Any]:
    value = payload.get(key)
    if not isinstance(value, dict):
        raise MalformedEventError(f"Payload missing '{key}' object")
    return value


def parse_issue_payload(payload: dict[str, Any]) -> IssueEvent:
    issue = _object(payload, "issue")
    if "pull_request" in issue:
        raise IgnoredEventError("Ignoring event because it is a pull request")

    action = payload.get("action")
    if not isinstance(action, str):
        raise MalformedEventError("Payload missing 'action' field")
    if action not in SUPPORTED_ACTIONS:
        raise IgnoredEventError(f"Ignoring unsupported action '{action}'")

    user = issue.get("user")
    if isinstance(user, dict) and user.get("type") == "Bot":
        raise IgnoredEventError("Ignoring event because it was generated by a bot")
    sender = payload.get("sender")
    if isinstance(sender, dict) and sender.get("type") == "Bot":
        raise IgnoredEventError("Ignoring event because it was triggered by a bot")

    repository = _object(payload, "repository")
    owner_payload = _object(repository, "owner")
    owner = owner_payload.get("login")
    repo = repository.get("name")
    issue_number = issue.get("number")
    title = issue.get("title")
    body = issue.get("body")
    html_url = issue.get("html_url")

    if not isinstance(owner, str) or not isinstance(repo, str):
        raise MalformedEventError("Repository owner or name is missing")
    if isinstance(issue_number, bool) or not isinstance(issue_number, int):
        raise MalformedEventError("Issue number is invalid")
    if not isinstance(title, str) or not isinstance(html_url, str):
        raise MalformedEventError("Issue title or html_url is missing")
    if body is not None and not isinstance(body, str):
        raise MalformedEventError("Issue body is invalid")

    return IssueEvent(
        owner=owner,
        repo=repo,
        issue_number=issue_number,
        title=title,
        body=body,
        action=action,
        html_url=html_url,
    )
