import json
import tempfile
import pytest
from kubetag.github.events import (
    parse_issue_event,
    parse_issue_payload,
    MalformedEventError,
    IgnoredEventError,
)

def test_valid_event_parsing() -> None:
    payload = {
        "action": "opened",
        "issue": {
            "number": 42,
            "title": "Bug in scheduling",
            "body": "Detailed description here",
            "html_url": "https://github.com/kubernetes/kubernetes/issues/42",
            "user": {"login": "alice", "type": "User"}
        },
        "repository": {
            "name": "kubernetes",
            "owner": {"login": "kubernetes"}
        }
    }
    event = parse_issue_payload(payload)
    assert event.owner == "kubernetes"
    assert event.repo == "kubernetes"
    assert event.issue_number == 42
    assert event.title == "Bug in scheduling"
    assert event.body == "Detailed description here"
    assert event.action == "opened"
    assert event.html_url == "https://github.com/kubernetes/kubernetes/issues/42"

def test_null_body_is_safe() -> None:
    payload = {
        "action": "edited",
        "issue": {
            "number": 100,
            "title": "Title with null body",
            "body": None,
            "html_url": "https://github.com/org/repo/issues/100",
            "user": {"login": "bob", "type": "User"}
        },
        "repository": {
            "name": "repo",
            "owner": {"login": "org"}
        }
    }
    event = parse_issue_payload(payload)
    assert event.body is None

def test_unsupported_action_raises_ignored() -> None:
    payload = {
        "action": "closed",
        "issue": {
            "number": 1,
            "title": "Closed issue",
            "body": "Body",
            "html_url": "url",
            "user": {"type": "User"}
        },
        "repository": {"name": "repo", "owner": {"login": "org"}}
    }
    with pytest.raises(IgnoredEventError, match="Ignoring unsupported action"):
        parse_issue_payload(payload)

def test_pull_request_raises_ignored() -> None:
    payload = {
        "action": "opened",
        "issue": {
            "number": 2,
            "title": "PR Title",
            "body": "PR Body",
            "html_url": "url",
            "pull_request": {},  # Denotes a PR
            "user": {"type": "User"}
        },
        "repository": {"name": "repo", "owner": {"login": "org"}}
    }
    with pytest.raises(IgnoredEventError, match="Ignoring event because it is a pull request"):
        parse_issue_payload(payload)

def test_bot_user_raises_ignored() -> None:
    payload = {
        "action": "opened",
        "issue": {
            "number": 3,
            "title": "Bot created issue",
            "body": "Body",
            "html_url": "url",
            "user": {"type": "Bot"}
        },
        "repository": {"name": "repo", "owner": {"login": "org"}}
    }
    with pytest.raises(IgnoredEventError, match="Ignoring event because it was generated by a bot"):
        parse_issue_payload(payload)

def test_malformed_event_missing_fields() -> None:
    payload = {
        "action": "opened",
        # missing issue
        "repository": {"name": "repo", "owner": {"login": "org"}}
    }
    with pytest.raises(MalformedEventError, match="missing 'issue' object"):
        parse_issue_payload(payload)

def test_parse_issue_event_from_file() -> None:
    payload = {
        "action": "reopened",
        "issue": {
            "number": 99,
            "title": "Reopened Issue",
            "body": "Body text",
            "html_url": "url",
            "user": {"type": "User"}
        },
        "repository": {"name": "repo", "owner": {"login": "org"}}
    }
    
    with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False, encoding="utf-8") as tmp:
        json.dump(payload, tmp)
        tmp_name = tmp.name

    try:
        event = parse_issue_event(tmp_name)
        assert event.issue_number == 99
        assert event.action == "reopened"
    finally:
        import os
        os.unlink(tmp_name)

def test_parse_issue_event_nonexistent_file() -> None:
    with pytest.raises(MalformedEventError, match="Event file not found"):
        parse_issue_event("/nonexistent/file/path.json")
